services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
        environment:
            - APP_ENV=local
        networks:
            - app-network
    scheduler:
        build:
            context: .
            dockerfile: docker/scheduler/Dockerfile
        container_name: my-laravel-scheduler
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./scheduler.sh:/scheduler.sh
        environment:
            - TZ=Asia/Kolkata
        networks:
            - app-network
        command: ["/bin/bash", "/scheduler.sh"]
        #  @Todo
    # mailhog:
    #     image: jcalonso/mailhog:latest
    #     ports:
    #         - "1025:1025" # SMTP server
    #         - "8025:8025" # Web UI
    #     networks:
    #         - app-network

    nginx:
        image: nginx:alpine
        container_name: my-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - app
        networks:
            - app-network

    node:
        platform: linux/arm64/v8
        build:
            context: .
            dockerfile: docker/node/Dockerfile.node
        image: my-laravel-node
        container_name: my-laravel-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - app-network

    db:
        platform: linux/arm64/v8
        image: mariadb:10.6
        container_name: my-mysql
        hostname: mysql
        restart: unless-stopped
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "127.0.0.1:3306:3306"

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
