FROM node:20

WORKDIR /var/www

COPY package*.json ./

RUN npm install

COPY . .

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
  CMD node -e "const http = require('http'); const options = { timeout: 2000, host: 'localhost', port: 3000, path: '/' }; const req = http.request(options, (res) => process.exit(res.statusCode >= 400 ? 1 : 0)); req.on('error', () => process.exit(1)); req.end()"


EXPOSE 3000

CMD ["npm", "run", "dev"]

ENTRYPOINT ["docker-entrypoint.sh"]
